Repository 0xPlaygrounds/rig, pull requests merged in 2024-11, with the labels that each got.

#85 test: add pre-commit & update gitignore
  .gitignore
  .pre-commit-config.yaml
Labels: chore, test

#86 devops: Add secrets to test CI job
  .github/workflows/ci.yaml
Labels: CI/CD

#56 feat(model-providers): 16 Add Gemini Completion and Embedding Models
  .github/workflows/ci.yaml
  README.md
  rig-core/README.md
  rig-core/examples/gemini_agent.rs
  rig-core/examples/gemini_embeddings.rs
  rig-core/src/embeddings.rs
  rig-core/src/providers/gemini/client.rs
  rig-core/src/providers/gemini/completion.rs
  rig-core/src/providers/gemini/embedding.rs
  rig-core/src/providers/gemini/mod.rs
  rig-core/src/providers/mod.rs
  rig-lancedb/README.md
Labels: model

#70 feat(vector-store): Add support for Neo4j
  Cargo.lock
  Cargo.toml
  rig-core/src/lib.rs
  rig-neo4j/CHANGELOG.md
  rig-neo4j/Cargo.toml
  rig-neo4j/LICENSE
  rig-neo4j/README.md
  rig-neo4j/examples/display/lib.rs
  rig-neo4j/examples/vector_search_movies_add_embeddings.rs
  rig-neo4j/examples/vector_search_movies_consume.rs
  rig-neo4j/examples/vector_search_simple.rs
  rig-neo4j/src/lib.rs
  rig-neo4j/src/vector_index.rs
Labels: vector store

#90 devops: Fix reusable CI workflow inherit secrets
  .github/workflows/cd.yaml
Labels: CI/CD

#93 docs: rig-core docs fixes and improvements
  rig-core/Cargo.toml
  rig-core/src/lib.rs
  rig-core/src/loaders/mod.rs
  rig-core/src/tool.rs
Labels: docs

#98 fix(rig-qdrant): Rig Qdrant dependency
  rig-qdrant/Cargo.toml
  rig-qdrant/README.md
  rig-qdrant/examples/qdrant_vector_search.rs
Labels: bug

#101 devops: Add rig-qdrant to workspace
  Cargo.lock
  Cargo.toml
  rig-qdrant/examples/qdrant_vector_search.rs
Labels: CI/CD

#100 Fix: Inefficient context documents serialization
  rig-core/examples/vector_search.rs
  rig-core/src/vector_store/in_memory_store.rs
  rig-core/src/vector_store/mod.rs
Labels: bug
