Repository 0xPlaygrounds/rig, pull requests merged in 2024-09, with the labels that each got.

#6 docs: Improve docstrings across the board
  Cargo.lock
  rig-core/Cargo.toml
  rig-core/src/agent.rs
  rig-core/src/cli_chatbot.rs
  rig-core/src/completion.rs
  rig-core/src/embeddings.rs
  rig-core/src/extractor.rs
  rig-core/src/lib.rs
  rig-core/src/model.rs
  rig-core/src/rag.rs
  rig-core/src/tool.rs
  rig-mongodb/Cargo.toml
  rig-mongodb/src/lib.rs
Labels: documentation

#7 devops: Add basic CI workflow
  .github/workflows/cd.yaml
  .github/workflows/ci.yaml
  rig-core/src/agent.rs
  rig-core/src/cli_chatbot.rs
  rig-core/src/completion.rs
  rig-core/src/embeddings.rs
  rig-core/src/extractor.rs
  rig-core/src/lib.rs
  rig-core/src/model.rs
  rig-core/src/tool.rs
  rig-mongodb/src/lib.rs
Labels: CI/CD

#8 Devops/setup ci cd
  .github/workflows/cd.yaml
Labels: CI/CD

#9 devops: Fix CD workflow
  .github/workflows/cd.yaml
Labels: CI/CD

#10 fix: workflows permissions
  .github/workflows/cd.yaml
  .github/workflows/ci.yaml
Labels: CI/CD

#18 feat(providers): Add Perplexity model provider
  rig-core/examples/perplexity_agent.rs
  rig-core/src/providers/mod.rs
  rig-core/src/providers/perplexity.rs
Labels: feat, model

#32 feat: Add utility methods to simplify InMemoryVectorStore creation
  rig-core/examples/vector_search.rs
  rig-core/src/vector_store/in_memory_store.rs
Labels: feat
