Repository 0xPlaygrounds/rig, pull requests merged in 2025-02, with the labels that each got.

#316 style: rename DeepSeek_R1.pdf to deepseek_r1.pdf
  rig-core/examples/documents/deepseek_r1.pdf
  rig-core/examples/pdf_agent.rs
Labels: non-breaking

#280 feat: surrealdb integration
  Cargo.lock
  Cargo.toml
  README.md
  rig-surrealdb/Cargo.toml
  rig-surrealdb/README.md
  rig-surrealdb/examples/migrations.surql
  rig-surrealdb/examples/vector_search_surreal.rs
  rig-surrealdb/src/lib.rs
Labels: vector store, non-breaking

#285 feat: add ollama client
  rig-core/Cargo.toml
  rig-core/examples/agent_with_ollama.rs
  rig-core/examples/image_ollama.rs
  rig-core/examples/images/camponotus_flavomarginatus_ant.jpg
  rig-core/examples/rag_ollama.rs
  rig-core/examples/vector_search_ollama.rs
  rig-core/src/providers/mod.rs
  rig-core/src/providers/ollama.rs
Labels: model, non-breaking

#322 feat: Transcription Model support
  Cargo.lock
  rig-core/Cargo.toml
  rig-core/examples/audio/en-us-natural-speech.mp3
  rig-core/examples/transcription.rs
  rig-core/src/lib.rs
  rig-core/src/providers/openai.rs
  rig-core/src/transcription.rs
Labels: non-breaking
