Repository 0xPlaygrounds/rig, pull requests merged in 2025-01, with the labels that each got.

#186 test: Mock provider API in vector store integration tests
  .github/workflows/ci.yaml
  Cargo.lock
  rig-core/src/embeddings/builder.rs
  rig-lancedb/Cargo.toml
  rig-lancedb/tests/integration_tests.rs
  rig-mongodb/Cargo.toml
  rig-mongodb/tests/integration_tests.rs
  rig-neo4j/Cargo.toml
  rig-neo4j/tests/integration_tests.rs
  rig-qdrant/Cargo.toml
  rig-qdrant/tests/integration_tests.rs
Labels: CI/CD, test

#190 test(rig-neo4j): Fix neo4j integration test
  rig-neo4j/tests/integration_tests.rs
Labels: CI/CD

#197 test(rig-neo4j): remove old tests
  rig-neo4j/src/lib.rs
Labels: CI/CD

#202 test(rig-sqlite): Add integration test
  Cargo.lock
  rig-sqlite/Cargo.toml
  rig-sqlite/src/lib.rs
  rig-sqlite/tests/integration_test.rs
Labels: test

#205 feat(model): add support for EternalAI onchain toolset
  Cargo.toml
  rig-core/src/completion.rs
  rig-core/src/providers/mod.rs
  rig-eternalai/Cargo.toml
  rig-eternalai/examples/agent_with_eternalai.rs
  rig-eternalai/src/eternalai_system_prompt_manager_toolset.rs
  rig-eternalai/src/json_utils.rs
  rig-eternalai/src/lib.rs
  rig-eternalai/src/providers/eternalai.rs
  rig-eternalai/src/providers/mod.rs
Labels: model

#240 docs(rig-eternalai): Add missing manifest fields + basic README
  Cargo.lock
  rig-eternalai/Cargo.toml
  rig-eternalai/README.md
Labels: docs, CI/CD
